### ISSUE TITLE
custom artwork?

### ISSUE THREAD

**Issue by densma1** [EvanPurkhiser/prolink-tools#35]
not really issue but feature request. wondering if its possible to add a feature that allows add one custom artwork to be used for all tracks with no artwork?
if no artwork available then display this one.

Thanks

**Comment by EvanPurkhiser** [comment]
Yes this is a good idea!

I will add support for this soon :)

**Comment by densma1** [comment]
thanks. looking forward to test

**Comment by EvanPurkhiser** [comment]
Actually, I think for this I would like to suggest using some custom CSS for the blank artwork.

If you're using OBS you can easily do this using the "custom CSS" section of the browser plugin:

![image](https://user-images.githubusercontent.com/1421724/99920116-3ba19200-2cd6-11eb-8a7c-ab236692d282.png)

I would recommend css like this:

```css
/* Empty track artwork is a div, not a `img` */
div.track-artwork {
	background-image: url('<url to your empty artwork>');
	background-size: cover;
}

/* Hide the empty artwork icon */
div.track-artwork svg {
	display: none;
}
```

---

I thought about the idea of making this configurable a little more, and think I might hold off on adding it unless some other chime in looking for it. But the CSS solution should work quite well 😃 

Let me know if you have any trouble with that!
